### ISSUE TITLE
Timeout error in live mode but not in sandbox mode

### ISSUE THREAD

**Issue by YoleyTeichman** [paypal/PayPal-NET-SDK#254]
Just put the application live and now experiencing a weird issue, GetAccessToken() does not work and throws back a timeout error after setting requestRetries = 3 and after 5 minutes of inactivity from the first call of GetAccessToken().

In other words, the first call of GetAccessToken() works fine but after 5 minutes of inactivity the request hangs and throws a timeout error,

I even changed the connectionTimeout to 360000 and didn't work either it just hangs until it times out.

Even tried the solutions mentioned here https://www.paypal-knowledge.com/infocenter/index?page=content&id=FAQ1750&actp=RSS but no luck.

I tried to refresh cache, from server and client didn't work either.

Can someone help me out here please as I knock in my head already over 4 days to figure out the problem and resolve it, but that's for sure that the problem is with 5 minutes of inactivity.

**Comment by pp-randy** [comment]
Are you able to provide the stack trace?  

After 2 minutes the SDK should be making a new request for an access token [OAuthTokenCredential.cs#L141-L163](https://github.com/paypal/PayPal-NET-SDK/blob/develop/Source/SDK/Api/OAuthTokenCredential.cs#L141-L163).

**Comment by YoleyTeichman** [comment]
Yes, 

```
The operation has timed out (HTTP request timeout was set to 30000ms)
   at PayPal.Api.HttpConnection.Execute(String payLoad, HttpWebRequest httpRequest)
   at PayPal.Api.PayPalResource.ConfigureAndExecute[T](APIContext apiContext, HttpMethod httpMethod, String resource, String payload, String endpoint, Boolean setAuthorizationHeader)
   at PayPal.Api.OAuthTokenCredential.GenerateOAuthToken()
   at PayPal.Api.OAuthTokenCredential.GetAccessToken()
   at EuropeanOutdoors.Library.Paypal.PaypalRequest.InitiateApiContext()
   at EuropeanOutdoors.Library.Paypal.PaypalInitiatePayment..ctor(PaypalPayment payment)
   at EuropeanOutdoors.BusinessLayer.Controllers.PaypalController.<GetPaypalCheckoutUrlAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EuropeanOutdoors.Controllers.CheckoutController.<PaypalCheckout>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EuropeanOutdoors.Controllers.CheckoutController.<CheckoutPhase>d__5.MoveNext()
```

Whats more interesting is when I try to debug it on my localhost with live mode I don't see any timeouts even after 5 minutes of inactivity.

**Comment by pp-randy** [comment]
Even more odd considering your first request works.  

Works on your localhost.  Are your .Net frameworks the same?  

Also do you have any way to capture the network traffic to see how far this failing request is getting?

**Comment by pp-randy** [comment]
It is unclear if other API calls would fail as well.  This seems like a sort of network issue, but if this turns out to be just an auth token request issue then you should know that the auth token has around an 8 hour time to live. https://developer.paypal.com/docs/api/auth-headers/
![image](https://cloud.githubusercontent.com/assets/6819909/25439764/fc763f82-2a62-11e7-96f1-7a68890655ce.png)

You might investigate increasing the cache value https://github.com/paypal/PayPal-NET-SDK/blob/develop/Source/SDK/Api/OAuthTokenCredential.cs#L125.  

Most likely other calls would fail even if you increased this cache time but you should be aware of the option. 

To be clear, when you have activity after 2 minutes it gets a new auth token just fine?

**Comment by YoleyTeichman** [comment]
.Net frameworks are the same on both, server and localhost, I'm still working on capturing network traffic will post it here the soon I get the trace,

We had problems before with one company that checks credit card fraud, which turns out an issue with their server not able to communicate with our server they resolve it by switching server.

I've also set AccessTokenExpirationInSeconds = 240 didn't work. Also tried setting the gap to different values didn't work either.

**Comment by YoleyTeichman** [comment]
> To be clear, when you have activity after 2 minutes it gets a new auth token just fine?

Yes, if we have activity within 5 minutes it stays alive until it gets 5 min of inactivity

**Comment by YoleyTeichman** [comment]
Whatever I tried no luck going further then the stack trace I've posted.

**Comment by pp-randy** [comment]
Have you already reached out to PayPal Technical Support as suggested here? https://github.com/paypal/PayPal-PHP-SDK/issues/481#issuecomment-296812410

If not, please do so here: http://www.paypal-techsupport.com/app/ask.  They will be better able to assist you with this.

**Comment by YoleyTeichman** [comment]
Yes, I have already did that 04/24/2017 01:39 PM, I'm waiting for a response.

**Comment by pp-randy** [comment]
What is the ticket number?

**Comment by YoleyTeichman** [comment]
Reference # 170424-000575

**Comment by pp-randy** [comment]
I wonder if you are running into an issue with the amount of connections or if they are not being disposed  properly.  
Maybe something similar to: http://stackoverflow.com/questions/5827030/httpwebrequest-times-out-on-second-call

**Comment by YoleyTeichman** [comment]
That is an interesting note, I'm checking to see whether its not getting disposed or just a connection issue.

Will post the results the soon I have them

**Comment by YoleyTeichman** [comment]
As I test it on a different code with another uri removing timeout properties it got through with results.
Is there a way I can get to the ServicePoint of the request from PayPalResource?

**Comment by YoleyTeichman** [comment]
I just got the error more precise

```
4/26/2017 1:16:45 PM:The operation has timed out (HTTP request timeout was set to 30000ms)
   at PayPal.Api.HttpConnection.Execute(String payLoad, HttpWebRequest httpRequest) in I:\Documents\PrimeScubaDocuments\PayPal\PayPal-NET-SDK-develop\Source\SDK\HttpConnection.cs:line 348
   at PayPal.Api.PayPalResource.ConfigureAndExecute[T](APIContext apiContext, HttpMethod httpMethod, String resource, String payload, String endpoint, Boolean setAuthorizationHeader) in I:\Documents\PrimeScubaDocuments\PayPal\PayPal-NET-SDK-develop\Source\SDK\Api\PayPalResource.cs:line 260
   at PayPal.Api.OAuthTokenCredential.GenerateOAuthToken() in I:\Documents\PrimeScubaDocuments\PayPal\PayPal-NET-SDK-develop\Source\SDK\Api\OAuthTokenCredential.cs:line 184
   at PayPal.Api.OAuthTokenCredential.GetAccessToken() in I:\Documents\PrimeScubaDocuments\PayPal\PayPal-NET-SDK-develop\Source\SDK\Api\OAuthTokenCredential.cs:line 160
   at EuropeanOutdoors.Library.Paypal.PaypalRequest.InitiateApiContext() in I:\PrimeScuba\EuropeanOutdoors\EuropeanOutdoors\EuropeanOutdoors.Library\Paypal\PaypalRequest.cs:line 23
   at EuropeanOutdoors.Library.Paypal.PaypalInitiatePayment..ctor(PaypalPayment payment) in I:\PrimeScuba\EuropeanOutdoors\EuropeanOutdoors\EuropeanOutdoors.Library\Paypal\PaypalInitiatePayment.cs:line 24
   at EuropeanOutdoors.BusinessLayer.Controllers.PaypalController.<GetPaypalCheckoutUrlAsync>d__5.MoveNext() in I:\PrimeScuba\EuropeanOutdoors\EuropeanOutdoors\EuropeanOutdoors.BusinessLayer\Controllers\PaypalController.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EuropeanOutdoors.Controllers.CheckoutController.<PaypalCheckout>d__8.MoveNext() in I:\PrimeScuba\EuropeanOutdoors\EuropeanOutdoors\EuropeanOutdoors\Controllers\CheckoutController.cs:line 243
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EuropeanOutdoors.Controllers.CheckoutController.<CheckoutPhase>d__5.MoveNext() in I:\PrimeScuba\EuropeanOutdoors\EuropeanOutdoors\EuropeanOutdoors\Controllers\CheckoutController.cs:line 201
```

**Comment by pp-randy** [comment]
I don't see `httpRequest` being exposed https://github.com/paypal/PayPal-NET-SDK/blob/develop/Source/SDK/Api/PayPalResource.cs#L160

Depending on what you are trying to do with ServicePoint, you could make changes here [SDK/Manager/ConnectionManager.cs#L57](https://github.com/paypal/PayPal-NET-SDK/blob/develop/Source/SDK/Manager/ConnectionManager.cs#L57).

**Comment by YoleyTeichman** [comment]
`httpRequest` is not being exposed, but perheps it stays open somehow before closing. Playing around with the link you sent me on stackoverflow.

**Comment by YoleyTeichman** [comment]
```
#if NET_4_5 || NET_4_5_1
            ServicePointManager.SecurityProtocol = ServicePointManager.SecurityProtocol | SecurityProtocolType.Tls12;
#else
```

I see you only support 4.5 or 4.5.1, I have version 4.5.2, does this make any difference?

**Comment by pp-randy** [comment]
That is only for security protocol to be TLS1.2 
You probably hit https://github.com/paypal/PayPal-NET-SDK/blob/develop/Source/SDK/Manager/ConnectionManager.cs#L42, but that is still having it use TLS1.2.

**Comment by YoleyTeichman** [comment]
After debugging step by step the system I got the httpRequest.GetResponse() which hangs and times out. Any Idea about that?

**Comment by YoleyTeichman** [comment]
I just realized that it doesn't matter if there is activity or not, it just times out and hangs after creating the first call after five minutes.

**Comment by xiaoleih41** [comment]
As it is not an actual SDK issue,  I have reached out to our merchant technical support team regarding the support ticket you have filed. They are looking into it right now and will have an engineer respond to you shortly.

**Comment by pp-randy** [comment]
Closing this issue as it has been resolved.

**Comment by YoleyTeichman** [comment]
I am reopening this issue as it is not resolved,
Just figured that it fails when trying to connect to one IP Address endpoint, 173.0.84.98 it creates a handshake but gets stuck, all other IP's are establishing connection successfully.

Any idea about that?

**Comment by pp-randy** [comment]
Have you updated your Technical Support ticket telling them you are still getting timeouts from this single IP Address endpoint?

**Comment by YoleyTeichman** [comment]
No, will do right now, Thanks

**Comment by YoleyTeichman** [comment]
Is there a way meanwhile to avoid this IP address by code?

**Comment by pp-randy** [comment]
I'm not sure of a easy way in code doing some research other than providing an IP Address directly; however, I can't advise you not to use DNS since the IP addresses do rotate.   

If you have the ability to exclude the IP in your DNS results that might be an option for you.  I did see some third party libraries google searching `C# customize dns entries` I can't really suggest any of them to you though.

**Comment by YoleyTeichman** [comment]
I have opened up a ticket 3 days ago but not response.

**Comment by pp-randy** [comment]
I have reached out regarding your ticket.

**Comment by pp-randy** [comment]
I have tested directly against the same IP address and cannot reproduce. Technical Support will be followup internally for you.
